#!/bin/bash
#
# This is a helpful script to call the status GitHub API

# Make sure enough parameters are added for this to work
if [ $# -lt 6 ]; then
    echo "Not enough params"
fi

REPO=$1
TOKEN=$2
COMMITREF=$3
STATE=$4
TARGET_URL=$5
DESCRIPTION=$6
CONTEXT=$7

curl https://api.github.com/repos/$REPO/statuses/$COMMITREF \
    -H "Content-Type: application/json" \
    -H "Authorization: token $TOKEN" \
    -X POST \
    -D header.file \
    -d "{\"state\": \"$STATE\", \"target_url\": \"$TARGET_URL\", \"description\": \"$DESCRIPTION\", \"context\": \"$CONTEXT\"}" 2> /dev/null > result.file

# Get the last HTTP Code and fail if it was not 200
RESPONSE=$(head -1 header.file | awk '{print $2}')
if [ $RESPONSE -ne "201" ]; then
    echo "Got unexpected HTTP code $RESPONSE"
    exit 1
fi

exit 0
